ai4co/rl4co

- rl4co/models/nn/utils.py
This update contains the implementation of the `RandomPolicy` class
The random policy constructs solutions with randomly chosen actions.
Having a random policy can be useful during the development of a new environment to perform the sanity check.
> Implement RandomPolicy

- rl4co/models/zoo/common/autoregressive/decoder.py
Pass td as an additional input of `_precompute_cache` to allow better  flexibility of `_precompute_cache` in the children classes
> Pass tensordict as an additional input of _precompute_cache

- rl4co/models/rl/reinforce/baselines.py
- tests/test_training.py
Add simple mean baseline.
Mean baseline is just calculated as the average of the rewards in a batch.
To add a simple baseline for model debugging.
`close #92`
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.
> [Feat] Mean baseline

- rl4co/envs/__init__.py
- rl4co/envs/smtwtp.py
- rl4co/models/nn/env_embeddings/context.py
- rl4co/models/nn/env_embeddings/dynamic.py
- rl4co/models/nn/env_embeddings/init.py
- rl4co/utils/test_utils.py
- tests/test_envs.py
- tests/test_policy.py
Add SMTWTP env and its env embeddings.
> Add SMTWTP env

- rl4co/models/zoo/pomo/model.py
Fix order of argument `shape` for `unbatchify` function in POMO Model.
The original argument for `shape` was `(n_start, n_aug)`, with which the shape of tensors will be changed to `[batch_size, n_start, n_aug]`. But we want it to be `[batch_size, n_aug, n_start]` so that it can mirror the batchify operation appropriately.
Note that the bug will not harm your training procedure or maximum reward calculation, but it should be fixed because it is not what we wanted, and make debugging difficult.
**I found that there's no test code for POMO though :(**
> Fix order of shape for unbatchify in POMO

- notebooks/tutorials/7-decoding-strategies.ipynb
- rl4co/models/nn/dec_strategies.py
- rl4co/models/zoo/common/autoregressive/decoder.py
- tests/test_policy.py
- added base DecodingStrategy class which defines the following functions
1. __pre_decoder_hook__: called before the while loop in the autoregressive decoder
2. __step__: is called in every iteration of the while loop and samples an action given the log probabilities. The actual logic is specified by the subclasses through a *_step* function
3. __post_decoder_hook__: called right after the while loop, mainly used to concatenate outputs
- implemented the greedy and sampling decoding strategies using the DecodingStrategy baseclass. They also support multistart by simply specifying "multistart_greedy" as decode_type for example. From a user perspective, nothing changes here.
- added beam search using the DecodingStrategy baseclass overwriting the following functions:
1. __pre_decoder_hook__: …
> [Feature] Add Beam Search as decoding strategy

- notebooks/tutorials/7-decoding-strategies.ipynb
Small fix in the markdown of the decoding strategies tutorial notebook
Greedy and beam search subsections were inverted
> [Notebooks] small markdown fix in decode strategies

- gnn.py
- pyproject.toml
- rl4co/models/__init__.py
- rl4co/models/nn/dec_strategies.py
- rl4co/models/nn/env_embeddings/__init__.py
- rl4co/models/nn/env_embeddings/edge.py
- rl4co/models/nn/graph/gcn.py
- rl4co/models/nn/graph/gnn.py
- rl4co/models/zoo/__init__.py
- rl4co/models/zoo/common/nonautoregressive/__init__.py
- rl4co/models/zoo/common/nonautoregressive/decoder.py
- rl4co/models/zoo/common/nonautoregressive/encoder.py
- rl4co/models/zoo/common/nonautoregressive/model.py
- rl4co/models/zoo/common/nonautoregressive/policy.py
- rl4co/utils/ops.py
- tests/test_training.py
Contributed by @Furffico, @tycbony, and @henry-yeh from DeepACO and GLOP. Adding new support for non-autoregressive (NAR) methods, including edge embedding methods for various environments, anisotropic GNN encoder with edge-gating mechanism, non-autoregressive decoder, and related utils functions. 
NAR methods are an important extension for RL4CO model support, aside from various previous autoregressive methods.
> [Feat] Nonautoregressive Methods

- rl4co/models/rl/reinforce/baselines.py
fixes #133
There are bugs in the warmup baseline, which
1.) lead to self.alpha values larger than 1 as soon as the epoch is larger than the number of warmup epochs. Instead, once the number of warmup epochs is exceeded, it should only return the value of the actual baseline. With this PR, self.alpha is only updated as long as the warmup epochs are not exceeded yet. 
2.) lead to wrong combination of baseline losses due to a misplaced parentheses
See also this PR: https://github.com/wouterkool/attention-learn-to-route/pull/56
Fixes the bugs mentioned above
> [BugFix] fix bugs in warmup baseline

- notebooks/tutorials/5-test-on-tsplib.ipynb
- notebooks/tutorials/6-test-on-cvrplib.ipynb
- rl4co/data/transforms.py
- rl4co/models/zoo/active_search/search.py
- rl4co/models/zoo/eas/search.py
- rl4co/models/zoo/matnet/model.py
- rl4co/models/zoo/pomo/model.py
- rl4co/models/zoo/symnco/model.py
- rl4co/tasks/eval.py
This PR contains the refactoring of the `StateAugmentation()` class for a more flexible, modularized way to choose different augmentation functions and augmentation features.  
As issue #139 raised by @aziabatz, using the `StateAugmentation()` to augment customized features is not intuitive. The default augmentation feature is `locs` for all environments, which may cause some bugs when working on customized environments without the `locs` feature. 
Besides, to make it more flexible and modularized for augment function selection, we replace the previous `use_dihedral_8: bool=False` with `augment_fn: Union[str, callable] = 'symmetric'` which allows users to use their own augmentation functions aside from given [symmetric augmentation …
> [Feat, Debug] Refactor augmentation class for flexible augment function and feature #139

- configs/env/mdcpdp.yaml
- rl4co/envs/__init__.py
- rl4co/envs/routing/__init__.py
- rl4co/envs/routing/mdcpdp.py
- rl4co/models/nn/env_embeddings/context.py
- rl4co/models/nn/env_embeddings/init.py
- tests/test_envs.py
The multi-depot capacity pickup and delivery problem (MDCPDP) environment has the following definition:
- The environment is made of `num_loc` + `num_depots` locations (cities):
- `num_depot` depot;
- `num_loc / 2` pickup locations;
- `num_loc / 2` delivery locations;
- The goal is to visit all the pickup and delivery locations in the shortest path possible starting from the depot;
- The conditions is that the agent must visit a pickup location before visiting its corresponding delivery location;
- The capacity is the maximum number of pickups that the vehicle can carry at the same time;
Aside from previous simple pickup and delivery (PDP) environment, this new environment supports the following new features:
1. *Multi depots*: there are more than one depot and each depot will have a …
> [Feat] Adding Multi-depot Capacity Pickup and Delivery Problem (MDCPDP) Environment

- rl4co/envs/routing/cvrp/env.py
- rl4co/envs/routing/cvrptw/env.py
In CVRP and CVRPTW, previously the size of `visited` is `[batch_size, 1, num_node]`. Now the size of `visited` is changed to `[batch_size, num_node]`.
All other environments use the size of `visited` with `[batch_size, num_node]`. Change the CVRP and CVRPTW's for the consequence. 
Also, the previous size `[batch_size, 1, num_node]` introduced a few expanding and squeezing operations, which are a bit massive and hard to read. Using the size of  `[batch_size, num_node]` could make the code clean.
> [Enhancement, Minor] Fix the `visited` shape of CVRP

- configs/model/pomo.yaml
- rl4co/models/zoo/am/decoder.py
Refactoring of the Attention model's decoder. 
By outsourcing the computation of glimpse_<q,k,v> and logit_k tensors into separate functions, we allow for more flexibility when reusing this decoder for other models. In scheduling for example, we need to select the embedding of the next operation for each job. This can now be achieved by simply overwriting the `_comput_kvl`function. 
> [Minor] Am decoder refactor

- rl4co/__init__.py
- rl4co/models/common/constructive/base.py
- rl4co/models/rl/ppo/ppo.py
- rl4co/models/zoo/ptrnet/decoder.py
- rl4co/utils/decoding.py
By not keeping only the logprobs of selected actions but all logprobs in the buffer of the decoding strategies, memory issues might occur. This is now fixed by adding an additional parameter `only_store_selected_logp` to the base decoding strategy, which defaults to True. Only exception is when we require the computation of the entropy (as in PPO). 
This fix should be backward compatible. We can still pass all logprobs to the `get_log_likelihood` function along with the actions, in which case this functions gathers the correct logprobs (like before).
see above
If you are unsure about any of these, don't hesitate to ask. We are here to …
> [BugFix] solve memory leakage during autoregressive decoding

- configs/experiment/scheduling/ffsp-matnet.yaml
- rl4co/data/dataset.py
- rl4co/envs/common/base.py
- rl4co/envs/scheduling/ffsp/env.py
- rl4co/envs/scheduling/ffsp/generator.py
- rl4co/models/zoo/matnet/decoder.py
- rl4co/models/zoo/matnet/encoder.py
- rl4co/models/zoo/matnet/policy.py
Fixes a bug in the augmentation of a FFSP instance, where stages were assigned the wrong machines in the `pre_step` of the environment. 
Also added marginally faster tensordict dataset which uses slightly (around 30%) more CPU and improved the MatNet code a little bit.
Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #15213` if this solves the issue #15213
- [x ] Bug fix (non-breaking change which fixes an issue)
> [BugFix] Fix a bug in the augmentation of FFSP instances

- examples/2d-meta_train.py
- rl4co/envs/common/distribution_utils.py
- rl4co/envs/common/utils.py
- rl4co/utils/__init__.py
- rl4co/utils/meta_trainer.py
- tests/test_training.py
Add a new training framework based on meta learning. Details refer to [Zhou et al. 2023](https://arxiv.org/abs/2305.19587). 
To address the generalization issue. 
> Add meta learning framework

- pyproject.toml
Enable to run "poetry install".
Update pyproject.toml to be enable to run `poetry install` and install rl4co project by poetry tool.
At current project, running `poetry install` may causes following errors.
```
The current project's Python requirement (>=3.8) is not compatible with some of the required packages Python requirement:
- pyvrp requires Python <4.0,>=3.9, so it will not be satisfied for Python >=3.8,<3.9 || >=4.0
- pyvrp requires Python <4.0,>=3.9, so it will not be satisfied for Python >=3.8,<3.9 || >=4.0
- pyvrp requires Python <4.0,>=3.9, so it will not be satisfied for Python >=3.8,<3.9 || >=4.0
Because no versions of pyvrp match >0.8.2,<0.9.0 || >0.9.0,<0.9.1 || >0.9.1
and pyvrp (0.8.2) requires Python <4.0,>=3.9, pyvrp is forbidden.
And because pyvrp (0.9.0) requires …
```
> [BugFix] python version

- examples/1-quickstart.ipynb
Modify Full documentation url `latest` to `stable` in example/1-quickstart.ipynb
When I click that url
```
Environment, Policy and Model
Full documentation of:
Base environment class [here](https://rl4co.readthedocs.io/en/latest/_content/api/envs/base.html)
Base policy class [here](https://rl4co.readthedocs.io/en/latest/_content/api/models/base.html)
Base model class [here](https://rl4co.readthedocs.io/en/latest/_content/api/algos/base.html)
```
the website shows this page
this cannot access rl4co's official docs directly, so i change latest url to corresponding stable url.
If you are unsure about any of these, don't hesitate to ask. …
> [DOCS] Modify url in example/1-quickstart.ipynb

- rl4co/data/generate_data.py
- rl4co/envs/routing/atsp/generator.py
Change the algorithm of tmat_class ATSP generation. Expect lower time and space complexity when producing the same result. 
See #225
> implement floyd on tmat_class atsp generation

- rl4co/models/zoo/matnet/decoder.py
This PR addresses an issue in the MatNet implementation where the positions of the row embedding and column embedding were swapped.
It is a significant model for handling matrices in NCO For more details, please refer to the ([original paper](https://arxiv.org/pdf/2106.11113))
> [Fix] fix the position of row and col embedding

- .gitignore
- LICENSE
- README.md
- docs/content/start/installation.md
- pyproject.toml
This is an update for the build system to the [preferred one by PyPa, i.e. `hatchling`](https://packaging.python.org/en/latest/tutorials/packaging-projects/#choosing-a-build-backend).
Also, we standardized the `pyproject.toml` with [this tool](https://github.com/mkniewallner/migrate-to-uv) to follow PEP 612. This also aligns with the release of [Poetry 2.0](https://python-poetry.org/blog/announcing-poetry-2.0.0/).
Another cool perk is that now with a single `pyproject.toml` we can offer the option to install with package managers including the new blazing-fast [`uv`](https://docs.astral.sh/uv/), [`poetry`](https://python-poetry.org/), or [`conda`](https://docs.conda.io/en/latest/).
> [Feat] Update build system

- configs/env/flp.yaml
- configs/env/mcp.yaml
- configs/experiment/graph/am.yaml
- rl4co/models/nn/env_embeddings/context.py
- rl4co/models/nn/env_embeddings/init.py
Bug fixes for #255.
Updated environment config files for the graph problems (FLP and MCP).
> [Bug fixes for #255] Added environment config files for FLP and MCP

- rl4co/models/zoo/symnco/model.py
Closes #254.
Further, the order of dimensions `(n_start, n_aug)` in `unbatchify()` in the `shared_step()` function was fixed to `(n_aug, n_start)` to be consistent with other models in the framework. Dimensions should be `[B, A, S]`, where `B` is the batch size, `A` the number of augmentations, and `S` the number of starts.
> Ensure baseline for SymNCO is always "symnco" when loading from checkpoint

- rl4co/envs/common/base.py
- rl4co/envs/eda/dpp/render.py
- rl4co/envs/eda/mdpp/render.py
- rl4co/envs/routing/atsp/render.py
- rl4co/envs/routing/cvrp/render.py
- rl4co/envs/routing/cvrptw/env.py
- rl4co/envs/routing/cvrptw/render.py
- rl4co/envs/routing/mdcpdp/render.py
- rl4co/envs/routing/mpdp/render.py
- rl4co/envs/routing/mtsp/render.py
- rl4co/envs/routing/mtvrp/render.py
- rl4co/envs/routing/op/render.py
- rl4co/envs/routing/pctsp/render.py
- rl4co/envs/routing/pdp/render.py
- rl4co/envs/routing/shpp/render.py
- rl4co/envs/routing/svrp/render.py
- rl4co/envs/routing/tsp/render.py
- rl4co/envs/scheduling/ffsp/render.py
- rl4co/envs/scheduling/fjsp/render.py
- rl4co/envs/scheduling/smtwtp/env.py
Commented our the two lines of code that set the limits for the x and y axis, respectively.
Assuming all locs would be scaled to [0,1] let to rendering problems for instances that were not in fact scaled to [0,1].
Closes #258 .
> Don't artificially limit the rendering axes for CVRP environment

- rl4co/envs/routing/mdcpdp/env.py
- rl4co/envs/routing/mdcpdp/generator.py
- rl4co/envs/routing/mdcpdp/render.py
- rl4co/models/nn/env_embeddings/context.py
- rl4co/models/nn/env_embeddings/init.py
These fixes are based on feedback from @Moonbohoon in #220 (which was due quite some time ago :sweat_smile: ) and updates to the parallel autoregressive counterpart of this environment in [PARCO](https://github.com/ai4co/parco).
Now `num_depot` is replaced with `num_agents`; each agent has its own starting node, which can be either in the same location (as in `single` depot) or with different locations (`multiple` depot). 
Below is an example to instantiate a model with the new env:
```python
import torch
from rl4co.utils.trainer import RL4COTrainer
from rl4co.envs.routing.mdcpdp.env import MDCPDPEnv, MDCPDPGenerator
from rl4co.models.zoo.am.policy import AttentionModelPolicy
from rl4co.models.nn.env_embeddings.init import MDCPDPInitEmbedding
from rl4co.models.nn.env_embeddings.context …
```
> [Feat] update MDCPDP env #220
